# Generated by Django 3.1.7 on 2021-09-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datawork', '0002_auto_20210906_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercode',
            name='code',
            field=models.IntegerField(),
        ),
    ]
